#!/bin/sh

echo "cljr help"
cljr help

echo "cljr list"
cljr list

echo "cljr search incanter"
cljr search incanter

echo "cljr describe incanter"
cljr describe incanter

echo "cljr versions incanter"
cljr versions incanter

echo "cljr install incanter"
cljr install incanter

echo "cljr list"
cljr list

echo "cljr add-classpath ~/Desktop/dev/incanter"
cljr add-classpath ~/Desktop/dev/incanter

echo "cljr classpath"
cljr classpath

echo "cljr list-jars"
cljr list-jars

echo "cljr run ~/Desktop/dev/incanter/examples/run_prob_plots.clj"
cljr run ~/Desktop/dev/incanter/examples/run_prob_plots.clj

echo "cljr repl"
cljr repl

echo "cljr swingrepl"
cljr swingrepl

echo "cljr swank"
cljr swank

echo "cljr remove-classpath ~/Desktop/dev/incanter"
cljr remove-classpath ~/Desktop/dev/incanter

echo "cljr remove incanter"
cljr remove incanter

echo "cljr list"
cljr list

echo "cljr clean"
cljr clean

echo "cljr reload"
cljr reload

